services:
  auth:
    build:
      context: ../
      dockerfile: ./apps/auth/Dockerfile
      target: development
    container_name: auth
    command: npm start auth
    env_file:
      - ./auth/.env
    environment:
      - TOKEN_REDIS_HOST=redis
      - THROTTLER_REDIS_HOST=redis
      - CORS_REDIS_HOST=redis
      - USERS_OAUTH_GRPC_URL=users:5002
    ports:
      - '3001:3001'
      - '5001:5001'
      - '5003:5003'
    volumes:
      - auth_data:/usr/src/app
    networks:
      - id-core-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  users:
    build:
      context: ../
      dockerfile: ./apps/users/Dockerfile
      target: development
    container_name: users
    command: npm start users
    env_file:
      - ./users/.env
    environment:
      - REDIS_HOST_VERIFICATION=redis
      - RMQ_HOST_USERS_NOTIFICATIONS=rabbitmq
      - AUTH_USERS_GRPC_URL=auth:5001
      - THROTTLER_REDIS_HOST=redis
    ports:
      - '3002:3002'
      - '5002:5002'
    volumes:
      - users_data:/usr/src/app
    networks:
      - id-core-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3002/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  notifications:
    build:
      context: ../
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    container_name: notifications
    command: npm start notifications
    env_file:
      - ./notifications/.env
    environment:
      - RMQ_HOST_USERS=rabbitmq
      - SMTP_HOST_USERS_ACTIVATE_USER=mailhog
      - SMTP_HOST_USERS_WELCOME_USER=mailhog
      - SMTP_HOST_USERS_VERIFY_LOGIN=mailhog
    ports:
      - '3003:3003'
    volumes:
      - notifications_data:/usr/src/app
    networks:
      - id-core-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3003/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  id-core-network:
    external: true

volumes:
  auth_data:
  users_data:
  notifications_data:
